import Listicon from "../../../../../assets/images/Group.png";
import emptycheck from '../../../../../assets/images/emptycheck.png'
const list = [
    {name:'Live Opportunities',image:Listicon},
    {name:'Upcoming Opportunities',image:Listicon},
    {name:'Pipeline',image:Listicon},
    {name:'Email Opportunities',image:Listicon},
    {name:'Recommended Opportunities',image:Listicon},
    {name:'Dashboard',image:Listicon},
    {name:'User Invitations',image:Listicon},
    {name:'Notifications',image:Listicon},
    {name:'Bid Amendment Alert',image:Listicon},
    {name:'Q&A Posting Alert',image:Listicon},
    {name:'Timeline Extension Alert',image:Listicon},
    {name:'Win Probability Prediction',image:Listicon},
    {name:'Incumbent details by Agencies',image:Listicon},
    {name:'Agency communication Management',image:Listicon},
    {name:'Teaming Partners Invitation',image:Listicon},
    {name:'Teaming Partner Collaboration',image:Listicon},
    {name:'Report Generation',image:Listicon},
    {name:'Agency Forecasts',image:Listicon},
    {name:'Spend & Analytics',image:Listicon},
    {name:'Resource & Events',image:Listicon},
    {name:'FAR library',image:Listicon},
    {name:'FOIA Request',image:Listicon},
    {name:'Multi Factor Authentication',image:Listicon},
    {name:'Email Support',image:Listicon},
    {name:'Phone Support',image:Listicon},
    {name:'Analyst Support',image:Listicon},
    {name:'Account Manager',image:Listicon},
]

export const basiclist = [
    {name:'Live Opportunities',image:Listicon},
    {name:'Upcoming Opportunities',image:Listicon},
    {name:'Pipeline',image:Listicon},
    {name:'Email Opportunities',image:Listicon},
    {name:'Recommended Opportunities',image:Listicon},
    {name:'Dashboard',image:Listicon},
    {name:'User Invitations',image:Listicon},
    {name:'Notifications',image:Listicon},
    {name:'Bid Amendment Alert',image:Listicon},
    {name:'Q&A Posting Alert',image:Listicon},
    {name:'Timeline Extension Alert',image:Listicon},
    {name:'Win Probability Prediction',image:emptycheck},
    {name:'Incumbent details by Agencies',image:emptycheck},
    {name:'Agency communication Management',image:emptycheck},
    {name:'Teaming Partners Invitation',image:emptycheck},
    {name:'Teaming Partner Collaboration',image:emptycheck},
    {name:'Report Generation',image:emptycheck},
    {name:'Agency Forecasts',image:emptycheck},
    {name:'Spend & Analytics',image:emptycheck},
    {name:'Resource & Events',image:emptycheck},
    {name:'FAR library',image:emptycheck},
    {name:'FOIA Request',image:emptycheck},
    {name:'Multi Factor Authentication',image:emptycheck},
    {name:'Email Support',image:emptycheck},
    {name:'Phone Support',image:emptycheck},
    {name:'Analyst Support',image:emptycheck},
    {name:'Account Manager',image:emptycheck},
]

export default list;