export const SIGNIN = 'SIGNIN'; 
export const AUTHENTICATED = 'AUTHENTICATED';
export const SIGNOUT = 'SIGNOUT';
export const SEND_MAIL_LINK_REQUEST = 'SEND_MAIL_LINK_REQUEST'; 
export const SEND_MAIL_LINK_SUCCESS = 'SEND_MAIL_LINK_SUCCESS';
export const SEND_MAIL_LINK_ERROR = 'SEND_MAIL_LINK_ERROR';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS'
export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILED = 'SIGNUP_FAILED'

export const CONTACT = 'Contact';
export const CONTACT_SUCCESS = 'Contact_SUCCESS'
export const CONTACT_FAILED = 'Contact_FAILED'

export const PLANS = 'PLANS';
export const PLANS_SUCCESS = 'PLANS_SUCCESS'
export const PLANS_FAILED = 'PLANS_FAILED'

export const SIGNUP_DATA = 'SIGNUP_DATA';
export const SIGNUP_DATA_SUCCESS = 'SIGNUP_DATA_SUCCESS';
export const SIGNUP_DATA_FAILED = 'SIGNUP_DATA_FAILED';

export const SHOW_AUTH_MESSAGE = 'SHOW_AUTH_MESSAGE'
export const HIDE_AUTH_MESSAGE = 'HIDE_AUTH_MESSAGE'
export const SHOW_LOADING = 'SHOW_LOADING'
export const AUTH_TOKEN = 'auth_token'
export const SIGNIN_WITH_GOOGLE = 'SIGNIN_WITH_GOOGLE'
export const SIGNIN_WITH_GOOGLE_AUTHENTICATED = 'SIGNIN_WITH_GOOGLE_AUTHENTICATED'
export const SIGNIN_WITH_FACEBOOK = 'SIGNIN_WITH_FACEBOOK'
export const SIGNIN_WITH_FACEBOOK_AUTHENTICATED = 'SIGNIN_WITH_FACEBOOK_AUTHENTICATED'

export const VERIFY = 'VERIFY'
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS'
export const VERIFY_FAILED = 'VERIFY_FAILED'

export const VERIFY_LOGIN = 'VERIFY_LOGIN'
export const VERIFY_LOGIN_SUCCESS = 'VERIFY_LOGIN_SUCCESS'
export const VERIFY_LOGIN_FAILED = 'VERIFY_LOGIN_FAILED'

export const CHANGE_PASSWORD__REQUESTED = 'CHANGE_PASSWORD__REQUESTED'
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST'
export const CHANGE_PASSWORD__SUCCESS = 'CHANGE_PASSWORD__SUCCESS'
export const CHANGE_PASSWORD__FAIELD = 'CHANGE_PASSWORD__FAIELD'

export const GET_USER_PROFILE = 'GET_USER_PROFILE'
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS'
export const GET_USER_PROFILE_FAILED = 'GET_USER_PROFILE_FAILED'


export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED'

export const PROFILE_ADD_USER = 'PROFILE_ADD_USER'
export const PROFILE_ADD_USER_SUCCESS = 'PROFILE_ADD_USER_SUCCESS'
export const PROFILE_ADD_USER_FAILED = 'PROFILE_ADD_USER_FAILED'

export const PROFILE_GET_USER = 'PROFILE_GET_USER'
export const PROFILE_GET_USER_SUCCESS = 'PROFILE_GET_USER_SUCCESS'
export const PROFILE_GET_USER_FAILED = 'PROFILE_GET_USER_FAILED'

export const  SUBSCRIPTION_PLAN = 'SUBSCRIPTION_PLAN'
export const SUBSCRIPTION_PLAN_SUCCESS = 'SUBSCRIPTION_PLAN_SUCCESS'
export const SUBSCRIPTION_PLAN_FAILED = 'SUBSCRIPTION_PLAN_FAILED'

export const STATE_DEATILS = 'STATE_DEATILS'
export const STATE_DEATILS_SUCCESS = 'STATE_DEATILS_SUCCESS'
export const STATE_DEATILS_FAILED = 'STATE_DEATILS_FAILED'


export const USERS_STATES = 'USERS_STATES'
export const USERS_STATES_SUCCESS = 'USERS_STATES_SUCCESS'
export const USERS_STATES_FAILED = 'USERS_STATES_FAILED'


export const UPDATE_ADDUSER_PROFILE = 'UPDATE_ADDUSER_PROFILE'
export const UPDATE_ADDUSER_PROFILE_SUCCESS = 'UPDATE_ADDUSER_PROFILE_SUCCESS'
export const UPDATE_ADDUSER_PROFILE_FAILED = 'UPDATE_ADDUSER_PROFILE_FAILED'

export const DELETE_REQUEST = 'DELETE_REQUEST';
export const DELETE_SUCCESS = 'DELETE_SUCCESS';
export const DELETE_FAILED = 'DELETE_FAILED';

export const CHANGE_PROFILE_PASSWORD = 'CHANGE_PROFILE_PASSWORD';
export const CHANGE_PROFILE_PASSWORD_SUCCESS = 'CHANGE_PROFILE_PASSWORD_SUCCESS';
export const CHANGE_PROFILE_PASSWORD_FAILED = 'CHANGE_PROFILE_PASSWORD_FAILED';

export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_FAILED = 'UPLOAD_IMAGE_FAILED';

export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILED = 'GET_PROFILE_FAILED';