
export const ALL_ALERTS_REQUEST = 'ALL_ALERTS_REQUEST';
export const ALL_ALERTS_REQUEST_SUCCESS = 'ALL_ALERTS_REQUEST_SUCCESS';
export const ALL_ALERTS_REQUEST_FAILED = 'ALL_ALERTS_REQUEST_FAILED';

export const MYOPPORTUNITY_REQUEST = 'MYOPPORTUNITY_REQUEST';
export const MYOPPORTUNITY_REQUEST_SUCCESS = 'MYOPPORTUNITY_REQUEST_SUCCESS';
export const MYOPPORTUNITY_REQUEST_FAILED = 'MYOPPORTUNITY_REQUEST_FAILED';

export const MYAGENCYALERTS_REQUEST = 'MYAGENCYALERTS_REQUEST';
export const  MYAGENCYALERTS_REQUEST_SUCCESS = ' MYAGENCYALERTS_REQUEST_SUCCESS';
export const  MYAGENCYALERTS_REQUEST_FAILED = ' MYAGENCYALERTS_REQUEST_FAILED';

export const TOP_AGENCY_SPENDS = 'TOP_AGENCY_SPENDS';
export const TOP_AGENCY_SPENDS_SUCCESS = 'TOP_AGENCY_SPENDS_SUCCESS';
export const TOP_AGENCY_SPENDS_FAILED = 'TOP_AGENCY_SPENDS_FAILED';

export const TEAMING_ALERTS_REQUEST = 'TEAMING_ALERTS_REQUEST';
export const TEAMING_ALERTS_SUCCESS = 'TEAMING_ALERTS_SUCCESS';
export const TEAMING_ALERTS_FAILED = 'TEAMING_ALERTS_FAILED';
