export const LIVE_OPPORTUNITY_REQUEST = 'LIVE_OPPORTUNITY_REQUEST';
export const LIVE_OPPORTUNITY_SUCCESS = 'LIVE_OPPORTUNITY_SUCCESS';
export const LIVE_OPPORTUNITY_FAILED = 'LIVE_OPPORTUNITY_FAILED';

export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_REQUEST_SUCCESS = 'SEARCH_REQUEST_SUCCESS';
export const SEARCH_REQUEST_FAILED = 'SEARCH_REQUEST_FAILED';