export const PIPLINE_REQUEST = 'PIPLINE_REQUEST';
export const PIPLINE_SUCCESS = 'PIPLINE_SUCCESS';
export const PIPLINE_FAILED = 'PIPLINE_FAILED';

export const PIPLINE_DELETE_REQUEST = 'PIPLINE_DELETE_REQUEST';
export const PIPLINE_DELETE_SUCCESS = 'PIPLINE_DELETE_SUCCESS';
export const PIPLINE_DELETE_FAILED = 'PIPLINE_DELETE_FAILED';

export const ADD_TO_PIPELINE_REQUEST = 'ADD_TO_PIPELINE_REQUEST';
export const ADD_TO_PIPELINE_SUCCESS = 'ADD_TO_PIPELINE_SUCCESS';
export const ADD_TO_PIPELINE_FAILED = 'ADD_TO_PIPELINE_FAILED';